apiVersion: batch/v1
kind: Job
metadata:
  name: demo-busybox
spec:
  template:
    spec:
      containers:
      - name: demo-busybox
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
